package cr.ac.una.icai.videojsf.clases;
// Generated 24-feb-2018 11:29:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AlquilerId generated by hbm2java
 */
public class AlquilerId  implements java.io.Serializable {


     private int cedula;
     private Date fecha;
     private int codigo;

    public AlquilerId() {
    }

    public AlquilerId(int cedula, Date fecha, int codigo) {
       this.cedula = cedula;
       this.fecha = fecha;
       this.codigo = codigo;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlquilerId) ) return false;
		 AlquilerId castOther = ( AlquilerId ) other; 
         
		 return (this.getCedula()==castOther.getCedula())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && (this.getCodigo()==castOther.getCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCedula();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + this.getCodigo();
         return result;
   }   


}


