package cr.ac.una.icai.videojsf.clases;
// Generated 24-feb-2018 11:29:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private AlquilerId id;
     private Cliente cliente;
     private Pelicula pelicula;
     private BigDecimal monto;
     private Integer dias;

    public Alquiler() {
    }

	
    public Alquiler(AlquilerId id, Cliente cliente, Pelicula pelicula) {
        this.id = id;
        this.cliente = cliente;
        this.pelicula = pelicula;
    }
    public Alquiler(AlquilerId id, Cliente cliente, Pelicula pelicula, BigDecimal monto, Integer dias) {
       this.id = id;
       this.cliente = cliente;
       this.pelicula = pelicula;
       this.monto = monto;
       this.dias = dias;
    }
   
    public AlquilerId getId() {
        return this.id;
    }
    
    public void setId(AlquilerId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Integer getDias() {
        return this.dias;
    }
    
    public void setDias(Integer dias) {
        this.dias = dias;
    }




}


