package cr.ac.una.icai.videojsf.clases;
// Generated 24-feb-2018 11:29:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private Integer telefono;
     private String direccion;
     private BigDecimal montoPagado;
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

    public Cliente() {
    }

	
    public Cliente(int cedula) {
        this.cedula = cedula;
    }
    public Cliente(int cedula, String nombre, Integer telefono, String direccion, BigDecimal montoPagado, Set<Alquiler> alquilers) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.montoPagado = montoPagado;
       this.alquilers = alquilers;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


