package cr.ac.una.icai.videojsf.clases;
// Generated 24-feb-2018 11:29:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String productora;
     private Integer tipo;
     private Integer taquillera;
     private Set<Actor> actors = new HashSet<Actor>(0);
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

    public Pelicula() {
    }

	
    public Pelicula(int codigo) {
        this.codigo = codigo;
    }
    public Pelicula(int codigo, String nombre, String productora, Integer tipo, Integer taquillera, Set<Actor> actors, Set<Alquiler> alquilers) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.productora = productora;
       this.tipo = tipo;
       this.taquillera = taquillera;
       this.actors = actors;
       this.alquilers = alquilers;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProductora() {
        return this.productora;
    }
    
    public void setProductora(String productora) {
        this.productora = productora;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public Integer getTaquillera() {
        return this.taquillera;
    }
    
    public void setTaquillera(Integer taquillera) {
        this.taquillera = taquillera;
    }
    public Set<Actor> getActors() {
        return this.actors;
    }
    
    public void setActors(Set<Actor> actors) {
        this.actors = actors;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


