package cr.ac.una.icai.videojsf.clases;
// Generated 24-feb-2018 11:29:37 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String user;
     private String password;

    public Usuario() {
    }

	
    public Usuario(String user) {
        this.user = user;
    }
    public Usuario(String user, String password) {
       this.user = user;
       this.password = password;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


