package cr.ac.una.icai.sicoca.clases;
// Generated 24-feb-2018 12:13:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int idArea;
     private String nombre;
     private String ubicacion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Area() {
    }

	
    public Area(int idArea) {
        this.idArea = idArea;
    }
    public Area(int idArea, String nombre, String ubicacion, Set<Empleado> empleados) {
       this.idArea = idArea;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.empleados = empleados;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


