package cr.ac.una.icai.sicoca.clases;
// Generated 24-feb-2018 12:13:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Instructor instructor;
     private String nombre;
     private Integer horasDuracion;
     private Date fechaInicio;
     private Date fechaFinalizacion;
     private BigDecimal precio;
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Curso() {
    }

	
    public Curso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Curso(int idCurso, Instructor instructor, String nombre, Integer horasDuracion, Date fechaInicio, Date fechaFinalizacion, BigDecimal precio, Set<Matricula> matriculas) {
       this.idCurso = idCurso;
       this.instructor = instructor;
       this.nombre = nombre;
       this.horasDuracion = horasDuracion;
       this.fechaInicio = fechaInicio;
       this.fechaFinalizacion = fechaFinalizacion;
       this.precio = precio;
       this.matriculas = matriculas;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getHorasDuracion() {
        return this.horasDuracion;
    }
    
    public void setHorasDuracion(Integer horasDuracion) {
        this.horasDuracion = horasDuracion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinalizacion() {
        return this.fechaFinalizacion;
    }
    
    public void setFechaFinalizacion(Date fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }




}


