package cr.ac.una.icai.sicoca.clases;
// Generated 24-feb-2018 12:13:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private int idInstructor;
     private String nombre;
     private String gradoAcademico;
     private Integer annosExperiencia;
     private String telefono;
     private String correo;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Instructor() {
    }

	
    public Instructor(int idInstructor) {
        this.idInstructor = idInstructor;
    }
    public Instructor(int idInstructor, String nombre, String gradoAcademico, Integer annosExperiencia, String telefono, String correo, Set<Curso> cursos) {
       this.idInstructor = idInstructor;
       this.nombre = nombre;
       this.gradoAcademico = gradoAcademico;
       this.annosExperiencia = annosExperiencia;
       this.telefono = telefono;
       this.correo = correo;
       this.cursos = cursos;
    }
   
    public int getIdInstructor() {
        return this.idInstructor;
    }
    
    public void setIdInstructor(int idInstructor) {
        this.idInstructor = idInstructor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }
    public Integer getAnnosExperiencia() {
        return this.annosExperiencia;
    }
    
    public void setAnnosExperiencia(Integer annosExperiencia) {
        this.annosExperiencia = annosExperiencia;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


