package cr.ac.una.icai.sicoca.clases;
// Generated 24-feb-2018 12:13:50 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int idCurso;
     private int cedula;

    public MatriculaId() {
    }

    public MatriculaId(int idCurso, int cedula) {
       this.idCurso = idCurso;
       this.cedula = cedula;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getIdCurso()==castOther.getIdCurso())
 && (this.getCedula()==castOther.getCedula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCurso();
         result = 37 * result + this.getCedula();
         return result;
   }   


}


