package cr.ac.una.icai.sicoca.clases;
// Generated 24-feb-2018 12:13:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Curso curso;
     private Empleado empleado;
     private BigDecimal nota;

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Curso curso, Empleado empleado) {
        this.id = id;
        this.curso = curso;
        this.empleado = empleado;
    }
    public Matricula(MatriculaId id, Curso curso, Empleado empleado, BigDecimal nota) {
       this.id = id;
       this.curso = curso;
       this.empleado = empleado;
       this.nota = nota;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


