package cr.una.una.icai.clases;
// Generated 17/02/2018 12:09:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idcurso;
     private Profesor profesor;
     private String nombre;
     private Integer creditos;
     private Set<Registro> registros = new HashSet<Registro>(0);
     private Set<Matricula> matriculas = new HashSet<Matricula>(0);

    public Curso() {
    }

	
    public Curso(int idcurso) {
        this.idcurso = idcurso;
    }
    public Curso(int idcurso, Profesor profesor, String nombre, Integer creditos, Set<Registro> registros, Set<Matricula> matriculas) {
       this.idcurso = idcurso;
       this.profesor = profesor;
       this.nombre = nombre;
       this.creditos = creditos;
       this.registros = registros;
       this.matriculas = matriculas;
    }
   
    public int getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }
    public Set<Matricula> getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set<Matricula> matriculas) {
        this.matriculas = matriculas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + this.idcurso;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Curso other = (Curso) obj;
        if (this.idcurso != other.idcurso) {
            return false;
        }
        return true;
    }




}


