package cr.una.una.icai.clases;
// Generated 17/02/2018 12:09:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Curso curso;
     private Estudiante estudiante;
     private BigDecimal nota;

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Curso curso, Estudiante estudiante) {
        this.id = id;
        this.curso = curso;
        this.estudiante = estudiante;
    }
    public Matricula(MatriculaId id, Curso curso, Estudiante estudiante, BigDecimal nota) {
       this.id = id;
       this.curso = curso;
       this.estudiante = estudiante;
       this.nota = nota;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


