package cr.una.una.icai.clases;
// Generated 17/02/2018 12:09:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int cedulaprofe;
     private String nombre;
     private Integer annosexperiencia;
     private String correo;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Profesor() {
    }

	
    public Profesor(int cedulaprofe) {
        this.cedulaprofe = cedulaprofe;
    }
    public Profesor(int cedulaprofe, String nombre, Integer annosexperiencia, String correo, Set<Curso> cursos) {
       this.cedulaprofe = cedulaprofe;
       this.nombre = nombre;
       this.annosexperiencia = annosexperiencia;
       this.correo = correo;
       this.cursos = cursos;
    }
   
    public int getCedulaprofe() {
        return this.cedulaprofe;
    }
    
    public void setCedulaprofe(int cedulaprofe) {
        this.cedulaprofe = cedulaprofe;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getAnnosexperiencia() {
        return this.annosexperiencia;
    }
    
    public void setAnnosexperiencia(Integer annosexperiencia) {
        this.annosexperiencia = annosexperiencia;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


