package cr.una.una.icai.clases;
// Generated 17/02/2018 12:09:47 PM by Hibernate Tools 4.3.1

/**
 * RegistroId generated by hbm2java
 */
public class RegistroId implements java.io.Serializable {

    private int ano;
    private int consecutivo;

    public RegistroId() {
    }

    public RegistroId(int ano, int consecutivo) {
        this.ano = ano;
        this.consecutivo = consecutivo;
    }

    public int getAno() {
        return this.ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    public int getConsecutivo() {
        return this.consecutivo;
    }

    public void setConsecutivo(int consecutivo) {
        this.consecutivo = consecutivo;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RegistroId)) {
            return false;
        }
        RegistroId castOther = (RegistroId) other;

        return (this.getAno() == castOther.getAno())
                && (this.getConsecutivo() == castOther.getConsecutivo());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getAno();
        result = 37 * result + this.getConsecutivo();
        return result;
    }

}
