package cr.una.una.icai.clases;
// Generated 17/02/2018 12:09:47 PM by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private RegistroId id;
     private Curso curso;
     private String observaciones;

    public Registro() {
    }

	
    public Registro(RegistroId id) {
        this.id = id;
    }
    public Registro(RegistroId id, Curso curso, String observaciones) {
       this.id = id;
       this.curso = curso;
       this.observaciones = observaciones;
    }
   
    public RegistroId getId() {
        return this.id;
    }
    
    public void setId(RegistroId id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Registro other = (Registro) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


